# Generated by Django 3.2.5 on 2023-06-10 15:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NeutrinoKey', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDataAtRestPostPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=32, unique=True)),
                ('title', models.CharField(default='Bruh, Change the Title', max_length=64)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('secure_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('result_nonce_text', models.CharField(default=b'AAAANw==', max_length=128)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secureblog_public_posts_author', to=settings.AUTH_USER_MODEL)),
                ('data_dek', models.ManyToManyField(default=1, related_name='data_dek_public', to='NeutrinoKey.DEK')),
                ('data_kek', models.ManyToManyField(default=1, related_name='data_kek_public', to='NeutrinoKey.KEK')),
                ('tags', models.ManyToManyField(related_name='secureblog_public_posts_tags', to='organizer.Tag')),
                ('tasking', models.ManyToManyField(related_name='securetasking_public', to='organizer.Tasking')),
            ],
            options={
                'verbose_name': '[Secure] blog public post',
                'ordering': ['-pub_date', 'title'],
                'permissions': (('view_future_post', 'Can view unpublished Post'), ('add_tasking', 'Can add task')),
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='SecureDataAtRestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=32, unique=True)),
                ('title', models.CharField(default='Bruh, Change the Title', max_length=64)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('secure_text', models.TextField(default='Please add Note Text')),
                ('result_nonce_text', models.CharField(default=b'AAAANw==', max_length=128)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secureblog_posts', to=settings.AUTH_USER_MODEL)),
                ('data_dek', models.ManyToManyField(default=1, related_name='data_dek', to='NeutrinoKey.DEK')),
                ('data_kek', models.ManyToManyField(default=1, related_name='data_kek', to='NeutrinoKey.KEK')),
                ('tags', models.ManyToManyField(related_name='secureblog_posts', to='organizer.Tag')),
                ('tasking', models.ManyToManyField(related_name='securetasking', to='organizer.Tasking')),
            ],
            options={
                'verbose_name': '[Secure] blog post',
                'ordering': ['-pub_date', 'title'],
                'permissions': (('view_future_post', 'Can view unpublished Post'), ('add_tasking', 'Can add task')),
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=64, unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='blog_posts', to='organizer.Tag')),
                ('tasking', models.ManyToManyField(related_name='tasking', to='organizer.Tasking')),
            ],
            options={
                'verbose_name': 'blog post',
                'ordering': ['-pub_date', 'title'],
                'permissions': (('view_future_post', 'Can view unpublished Post'), ('add_tasking', 'Can add task')),
                'get_latest_by': 'pub_date',
            },
        ),
    ]
