# Generated by Django 3.1.7 on 2021-07-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=64, unique_for_month='pub_date')),
                ('text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'verbose_name': 'blog post',
                'ordering': ['-pub_date', 'title'],
                'permissions': (('view_future_post', 'Can view unpublished Post'), ('add_tasking', 'Can add task')),
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='SecureDataAtRestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=32, unique=True)),
                ('title', models.CharField(default='Bruh, Change the Title', max_length=64)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('secure_text', models.TextField(default='Please add Note Text')),
                ('result_nonce_text', models.CharField(default=b'AAAANw==', max_length=128)),
                ('is_encrypted', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '[Secure] blog post',
                'ordering': ['-pub_date', 'title'],
                'permissions': (('view_future_post', 'Can view unpublished Post'), ('add_tasking', 'Can add task')),
                'get_latest_by': 'pub_date',
            },
        ),
    ]
