# Generated by Django 3.1.7 on 2021-07-27 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0001_initial'),
        ('NeutrinoKey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedataatrestpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secureblog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securedataatrestpost',
            name='data_dek',
            field=models.ManyToManyField(default=1, related_name='data_dek', to='NeutrinoKey.DEK'),
        ),
        migrations.AddField(
            model_name='securedataatrestpost',
            name='data_kek',
            field=models.ManyToManyField(default=1, related_name='data_kek', to='NeutrinoKey.KEK'),
        ),
        migrations.AddField(
            model_name='securedataatrestpost',
            name='tags',
            field=models.ManyToManyField(related_name='secureblog_posts', to='organizer.Tag'),
        ),
        migrations.AddField(
            model_name='securedataatrestpost',
            name='tasking',
            field=models.ManyToManyField(related_name='securetasking', to='organizer.Tasking'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='blog_posts', to='organizer.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tasking',
            field=models.ManyToManyField(related_name='tasking', to='organizer.Tasking'),
        ),
    ]
