# Generated by Django 3.2.5 on 2023-06-10 15:31

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NeutrinoKey', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tasking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('asignee', models.CharField(db_index=True, max_length=16)),
                ('project_codename', models.CharField(db_index=True, default='SandStorm', max_length=32)),
                ('description', models.TextField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True, unique=True, verbose_name='date assigned')),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'assigned_date',
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/home/bd007/projects/internet_bitbucket/housedeblake/FortressOfSolitude/_FortressOfSolitude/superhero/static/media/video/'), upload_to='')),
                ('result_nonce_file', models.CharField(default=b'AAAANw==', max_length=128)),
                ('data_dek', models.ManyToManyField(default=1, to='NeutrinoKey.DEK')),
                ('data_kek', models.ManyToManyField(default=1, to='NeutrinoKey.KEK')),
            ],
            options={
                'ordering': ['-image_file'],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=32, unique=True)),
                ('description', models.TextField()),
                ('founded_date', models.DateField(verbose_name='date founded')),
                ('contact', models.EmailField(max_length=254)),
                ('website', models.URLField(max_length=64)),
                ('tags', models.ManyToManyField(to='organizer.Tag')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'founded_date',
            },
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('link', models.URLField(max_length=64)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.startup')),
            ],
            options={
                'verbose_name': 'news article',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/home/bd007/projects/internet_bitbucket/housedeblake/FortressOfSolitude/_FortressOfSolitude/superhero/static/media/music/'), upload_to='')),
                ('result_nonce_file', models.CharField(default=b'AAAANw==', max_length=128)),
                ('data_dek', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NeutrinoKey.dek')),
                ('data_kek', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NeutrinoKey.kek')),
            ],
            options={
                'ordering': ['image_file'],
            },
        ),
        migrations.CreateModel(
            name='MiscFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/home/bd007/projects/internet_bitbucket/housedeblake/FortressOfSolitude/_FortressOfSolitude/superhero/static/media/otherfiles/'), upload_to='')),
                ('result_nonce_file', models.CharField(default=b'AAAANw==', max_length=128)),
                ('data_dek', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NeutrinoKey.dek')),
                ('data_kek', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NeutrinoKey.kek')),
            ],
            options={
                'ordering': ['-image_file'],
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/home/bd007/projects/internet_bitbucket/housedeblake/FortressOfSolitude/_FortressOfSolitude/superhero/static/media/photos/'), upload_to='')),
                ('result_nonce_file', models.CharField(default=b'AAAANw==', max_length=128)),
                ('data_dek', models.ManyToManyField(default=1, to='NeutrinoKey.DEK')),
                ('data_kek', models.ManyToManyField(default=1, to='NeutrinoKey.KEK')),
            ],
            options={
                'ordering': ['-image_file'],
            },
        ),
    ]
