# Generated by Django 3.1.7 on 2021-07-27 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_wrapped_nonce', models.CharField(default=b'AAAANw==', max_length=128)),
                ('result_wrappedDek', models.CharField(max_length=128)),
                ('result_SALT', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'DEK',
            },
        ),
        migrations.CreateModel(
            name='KEK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_wrapped_nonce', models.CharField(default=b'AAAANw==', max_length=128)),
                ('result_wrapped_kek', models.CharField(default=None, max_length=128)),
            ],
            options={
                'verbose_name': 'KEK',
            },
        ),
        migrations.CreateModel(
            name='NeutronCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_generated', models.DateTimeField(auto_now_add=True, verbose_name='date star collapsed')),
            ],
            options={
                'verbose_name': 'neutron core',
                'ordering': ['-time_generated'],
                'get_latest_by': 'time_generated',
            },
        ),
        migrations.CreateModel(
            name='NeutronMatterCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_generated', models.DateTimeField(auto_now_add=True, verbose_name='date integrated')),
                ('dek', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DEK_obj', to='NeutrinoKey.dek')),
                ('dekgenerator', models.ManyToManyField(related_name='kek_for_dek_generator', to='NeutrinoKey.DEK')),
                ('kekForDek', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='KEK_obj', to='NeutrinoKey.kek')),
            ],
            options={
                'verbose_name': 'neutron matter collector',
                'ordering': ['-time_generated'],
                'get_latest_by': 'time_generated',
            },
        ),
    ]
