# Generated by Django 3.1.7 on 2021-07-27 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NeutrinoKey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neutroncore',
            name='kek',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='KEK', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neutroncore',
            name='kekgenerator',
            field=models.ManyToManyField(related_name='KEK', to='NeutrinoKey.KEK'),
        ),
        migrations.AddField(
            model_name='dek',
            name='kek_to_retrieve',
            field=models.ManyToManyField(to='NeutrinoKey.KEK'),
        ),
    ]
